### ISSUE TITLE
branch in DTLO_table 

### ISSUE THREAD

**Issue by yikiii** [Tancata/phylo#2]
hi, I have a question.
the internal nodes in the DTLO_table  are numbers:
Branch	Duplications	Transfers	Losses	Originations	CopyNum
**216**	16.53	2.23	9.74	0.06	93.08
**217**	19.5	0.47	42.32	0.0	103.57
**199**	12.0	2.0	28.07	0.14	52.43
**215**	2.57	0.36	7.9	0.0	49.5
**212**	6.02	3.8	18.43	0.03	61.02

how can I know their location on the tree?

Looking forward to your reply, thank you!

**Comment by Tancata** [comment]
Hi Yikii, 

if you look at the third line of a *rec file (starting with "S:"), you'll see a version of the rooted species tree where these numbers are mapped to the internal nodes of the tree. If you open that tree in e.g. FigTree and turn on the labels, you'll see the mapping --- hope this helps.

**Comment by yikiii** [comment]
It is helpful to me! 
It's so kind of you! Thank you!
