### ISSUE TITLE
Help with error when generating ancestor rebuild on a given branch

### ISSUE THREAD

**Issue by wanxn518** [Tancata/phylo#3]
Hi Tancata,

Thank you for these useful scripts about ALE, it's very useful for newbies like me!
I'm having a bit of a problem trying to To produce an ancestor reconstruction at a given branch. 
[test.tar.gz](https://github.com/user-attachments/files/15737667/test.tar.gz)

I'm trying to do an ancestor reconstruction on node 101 (ALEml_undated) using gene_copies_at_node.py with the output file in the test_uml_rec file, but I get this error when running. "cat small_rec_representative.fa : No such file or directory" By definition, he should execute "cat medoid/OG0002145_representative.fa",I don't I don't know why.

Can you give me some suggestions? Thank you sincerely in advance for any help.

Attached here is my data and the script used

Best,
xnw

```
python2.7 gene_copies_at_node.py test_uml_rec/ 101 output 0.5

cat: medoid/small_rec_representative.fa: No such file or directory
small_rec.fa    1
cat: medoid/small_rec_representative.fa: No such file or directory
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    8.63
cat: medoid/small_rec_representative.fa: No such file or directory
small_rec.fa    0.01
small_rec.fa    0
small_rec.fa    0
small_rec.fa    1.07
cat: medoid/small_rec_representative.fa: No such file or directory
small_rec.fa    0
small_rec.fa    0
small_rec.fa    1.01
cat: medoid/small_rec_representative.fa: No such file or directory
small_rec.fa    0
small_rec.fa    0.01
small_rec.fa    0.01
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0.01
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0.01
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0.01
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    2
cat: medoid/small_rec_representative.fa: No such file or directory
small_rec.fa    0.01
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    0
small_rec.fa    2.15
cat: medoid/small_rec_representative.fa: No such file or directory
Total gene copies at node: 2522.88
```
```
cat gene_copies_at_node.py
#from ALE reconciliations, extract the number of copies for each gene family at a specified node on the tree (supplied by a node number)
#python gene_copies_at_node.py reconciliation_file_dir node_number protein_outputfile anc_reconstruction_threshold(num copies)
import re, os, sys

directory = sys.argv[1]
node = int(sys.argv[2])
predicted_proteome_output_file = sys.argv[3]
ancestral_threshold = float(sys.argv[4])
total_num_gene_copies = 0

if os.path.exists(predicted_proteome_output_file):
    os.unlink(predicted_proteome_output_file)

to_parse = [file for file in os.listdir(directory) if file.endswith("uml_rec")]
print "GeneFam\tCopies"
for file in to_parse:
    name_fields = re.split("_", file)
    fam_name = ''
    representative_name = ''
    if file.startswith("fix"):
        fam_name = name_fields[1] + ".fa"
        representative_name = name_fields[1] + "_representative.fa"
    else:
        fam_name = "small_" + name_fields[1] + ".fa"
        representative_name = "small_" + name_fields[1] + "_representative.fa"
    inh = open(directory + file)
    for line in inh:
        fields = re.split("\t", line.rstrip())
        if len(fields) > 1:
            if fields[0] == "S_internal_branch" and int(fields[1]) == node:
                print fam_name + "\t" + str(fields[-1])
                total_num_gene_copies += float(fields[-1])
                #if above the threshold for including in the node protein content reconstruction, do so now
                if float(fields[-1]) >= ancestral_threshold:
                    os.system("cat medoid/" + representative_name + " | { cat; echo; } >> " + predicted_proteome_output_file)

    inh.close()
print "Total gene copies at node: " + str(total_num_gene_copies)

```

**Comment by Tancata** [comment]
Hello xnw,

this is because that script is hard-coded to expect a certain format in the input uml_rec file names (you can see that it tries to find underscores in the name to get a sort of tag for each gene family). I would suggest one of two things: I've just uploaded a simpler version of the script, gene_copies_simple.py, to the same folder which works on your test data, and is also modified for Python 3. The (perhaps better) alternative would be to check out one of the other sets of helper scripts for ALE that have been written in the 5+ years since I wrote these old ones. For example Adrian Davin has a nice repository here: https://github.com/AADavin/ALEtutorial

You might also consider migrating to AleRax when you find it convenient (https://github.com/BenoitMorel/AleRax). Future development of ALE-type models is probably going to be mostly in that program (currently under lots of exciting development...), and it is also faster, more efficient, and has more options for specifying models than ALE.

All the best for now,

Tom

**Comment by wanxn518** [comment]
Hi Tancata,
Thank you so much for your reply and help, it has helped me a lot. Now I have been able to perform ancestral gene content reconstructions successfully, it's so good. I read your instructions in ALEtutorialPublic and it is very obvious how helpful it is for newbies. But I'm having a problem with reconcilation using fraction_missing.
When I provide the fraction_missing file for ALEml_undated, the run doesn't even produce the uml_rec 
```
(base) ➜  test docker run -v $PWD:$PWD  -w $PWD boussau/alesuite ALEml_undated species.tree OG0002260.treefile.ale separators=+ fraction_missing=fraction_missing.txt
ALEml_undated using ALE v0.4
Read species tree from: species.tree..
Read summary of tree sample for 1 trees from: OG0002260.treefile.ale..
# File containing fractions of missing genes set to fraction_missing.txt
0.710000 7.750000 4.800000 2.030000 3.240000 19.710000 3.770000 2.600000 2.130000 10.900000 19.230000 5.970000 12.200000 26.940000 10.490000 3.730000 14.790000 14.930000 0.780000 4.990000 2.030000 2.310000 4.450000 12.050000 8.490000 15.090000 18.030000 4.530000 7.390000 5.380000 7.810000 14.200000 18.000000 11.340000 8.170000 0.000000 5.690000 5.180000 3.350000 9.650000 6.230000 1.190000 13.070000 2.510000 13.410000 3.350000 7.360000 2.040000 2.770000 0.000000 0.000000 0.000000 10.290000 2.340000 2.570000 7.150000 18.700000 2.830000 5.850000 3.670000 11.380000 5.780000 6.800000 7.100000 13.450000 4.230000 7.250000 1.220000 12.790000 8.680000 10.940000 2.700000 3.830000 18.220000 2.340000 2.080000 3.490000 6.560000 8.930000 12.380000 15.220000 13.790000 3.210000 0.120000 7.150000 16.280000 13.860000 2.010000 12.090000 7.720000 3.770000 6.780000
Reconciliation model initialised, starting DTL rate optimisation..
#optimizing delta rate
#optimizing tau rate
#optimizing lambda rate
#optimizing rates
Optimizing... \ 4999
ML rates:  delta=0.010000; tau=0.010000; lambda=0.100000.
LL=-nan
Sampling reconciled gene trees..

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*terminate called after throwing an instance of 'bpp::Exception'
  what():  TreeTemplateTools::parenthesisToTree(). Bad format: no semi-colon found.
```
Dear Tancata, do you have any suggestions for this? Sincere thanks in advance!

I wish you all the best.
xnw

**Comment by Tancata** [comment]
Hi xnw,

yes, the fraction missing values must be between 0 and 1, e.g. 1-(fraction complete). So if 1% of the genes are missing, it would be 0.01. Hope this helps.

**Comment by wanxn518** [comment]
Hi Tancata, Thank you very much, my problem is solved, you're a really nice person, I wish you all the best!

**Comment by wanxn518** [comment]
Hi Tancata,

I'm sorry I'm bothering you again. I've looked at some of your help files on github and they are really useful. Also I looked at the application of ALE results in related articles, including "Gene duplication drives genome expansion in a major lineage of Thaumarchaeota" " Recovery of Lutacidiplasmatales archaeal order genomes suggests convergent evolution in Thermoplasmatota" "Genomics of Genomics of soil depth niche partitioning in the Thaumarchaeota family Gagatemarchaeaceae" and so on, but I have some problems, can you give me some help? Thank you sincerely in advance.

We know that the ALE results tell us the replication, transfer, origin, loss and gene copy number of each gene family in each ancestral node. As mentioned in the three papers above which genes were gained and lost by specific ancestral nodes "The Gagatemarchaeaceae LCA gained many key genes relevant for their adaptation to soil environments, including seven peptidases (families S33, S09X, M95, N11, S33, M50B and M03C) and four genes involved in the utilisation of myo-inositol (iolB, C, E and G)".

I would like to know how to define the gain and loss of genes? For genes gained and lost in a particular ancestral node (e.g. S_internal_branch 90), is it determined by the statistics of duplication, transfer, origin, and loss events of the different gene families in that node? (Several references consider the INFERRED FREQUENCY IS OVER 0.3 as a threshold for the event to occur.) If, for example, 1000 gene families have had a gene acquisition event (replication, transfer, and origin frequency over 0.3) at the 90 ancestor node, can all of these 1000 gene families be considered to be genes acquired by the 90 ancestor? Another approach would be to compare the gene families reconstructed at the 90 ancestor node with those reconstructed at a node in the progeny to determine which genes were lost and gained in the transition from the 90 node to the progeny? Which method is correct? Do you have a good suggestion yet?

Sorry ah, I may be a bit long-winded as I'm afraid I can't make my question clear. Thank you very much indeed!


Best wishes,
xnw

**Comment by Tancata** [comment]
Hi xnw,

yes, this is a good question, and various papers using reconciliation methods have handled it differently. The basic point is that, by default, ALE averages the count of events (such as gene losses on the branch leading to a given node) over 100 reconciliations. So 0.2 losses in a gene family at a node mean that, in 20 of those 100 sampled reconciliations, the gene was lost on the branch leading to that node. 

How you want to summarise or use that information might depend on your goal. For example, if you want to ask how many genes in total were lost on the branch leading to node X, and you had reconciliations for all of the genes on the genome, you could just sum the number of losses at that node over all of the families. If you really care about times when a specific gene was lost, then you can view the (fractional) number of losses as something like a probability of loss, but with the important caveat that if the family is multi-copy, the interpretation would not really be entirely true: that is, if a gene is usually either present in one copy or not, and has 0.7 losses on a branch, then you might conclude that there's roughly a 70% chance it was lost there. But if it is often found in 10 copies, then it may be just that the copy number changed a bit. 

Sometimes people have used some thresholds when considering specific genes of interest - .e.g, if gene X is the key gene needed for metabolism Y, and it is present with >0.5 probability on branch Z, then maybe we can conclude that this ancestor could possibly do the metabolism, if we are happy with a 0.5 threshold. I definitely wouldn't use thresholds when summing events - just sum the number of copies, or number of events, or probabilities directly. Thresholding the individual events (i.e., applying a sort of recoding where <0.3 = 0 and >0.3 = 1) probably is not the best approach...

**Comment by wanxn518** [comment]
Dear Tancata,

I am deeply grateful for your response, it really helped me a lot, I thought carefully about what you said and it really makes sense.

Based on the ALE results, I did a gene reconstruction (using gene_copies_simple.py) of the two ancestral branches 172 and 177, as shown in the figure, the numbers in the table represent the "copies" of each OG family corresponding to the branches 172 and 177, can I interpret it as the number of copies of that gene family?

Suppose the answer is yes. What genes were acquired during the evolutionary process from 172 to 177 (shown below), and is it possible to compare the "copies" of each gene family in the two branches? The reference states that "more than 0.5 reconciliation copies are considered to be present in this ancestral branch". So taking the OG0000061 gene family as an example (in the figure below), from 172 to 177, it is a process from nothing to something, so I can say that the evolution from 172 to 177 has resulted in the OG0000061 gene family, right?

I'm sorry that I left a bit too much text, because I really cherish every opportunity to communicate with you, and every time I can solve some of my confusion. Thank you very, very much! You are really enthusiastic.

With sincere gratitude,
xnw
![image](https://github.com/Tancata/phylo/assets/97587984/1c7cefe6-fc24-4acd-b762-96c96813b5f1)

**Comment by Tancata** [comment]
Hi xnw, yes, your interpretation here is reasonable. There is a gain of 6.02-0.27=5.75 gene copies on the branch from 172 to 177 (assuming they are two ends of the same branch), so it increased a lot in copy number there. Whether it originated there or was acquired by HGT from elsewhere is a separate matter that you could possibly look at via originations, although they might well be quite diffuse.

**Comment by wanxn518** [comment]
Thank you very much for your reply, I understand now. 
Best,
xnw
